name: gg
channels:
  - conda-forge
dependencies:
  - cudatoolkit=11.1
  - moviepy
  - ninja
  - numpy
  - pandas
  - pillow
  - pip
  - plotly
  - python=3.9
  - python-lmdb
  - pytorch=1.9.0
  - scikit-learn
  - scipy
  - tensorboard>=1.15
  - termcolor
  - torchvision=0.10.0
  - tqdm
  - pip:
    - opencv-python
    - ray
